# Site Params

# Open Graph, Twitter Cards and schema.org Thing and Article (in posts)
# https://gohugo.io/templates/internal/#open-graph
# https://gohugo.io/templates/internal/#twitter-cards
# https://schema.org/Thing
# https://schema.org/Article
description = "The home of Westminster Astronomical Society"
images = ['images/WASI-3.svg', 'images/site-feature-image.png']
mainMenuLogo = "images/WASI-3.svg"

# For favicons
## Chrome Browser
themeColor = "#212529"

# Alert
alert = false
alertDismissable = true
alertText = "An Announcement! <a class=\"alert-link stretched-link\" href=\"https://example/\">Click here</a>"

# Pre-footer
footerAbout = true
footerAboutTitle = ""
footerAboutText = ""

[options]
bootStrapJs = true
breadCrumb = true
listCategoryFilter = true
listTagFilter = true
