[[main]]
name = "Home"
url = ""
weight = 10

[[main]]
name = "About"
url = "about"
weight = 20
title = "About Westminster Astronomical Society"

[[main]]
name = "Events"
url = "https://nightsky.jpl.nasa.gov/events/wasi/"
weight = 20
title = "WASI Night Sky Network Calendar"

[[main]]
identifier = "observatory"
name = "Observatory"
url = "observatory"
weight = 40
title = "WASI Observatory"

[[main]]
identifier = "planetarium"
name = "Planetarium"
url = "planetarium"
weight = 50
title = "Bear Branch Planetarium"

[[main]]
identifier = "membership"
name = "Membership"
url = "membership"
weight = 60
title = "Join the Westminster Astronomical Society"

[[main]]
identifier = "resources"
name = "Resources"
weight = 70
title = "Astronomy Resources"

[[main]]
  name = "Almanac"
  url = "almanac"
  weight = 5
  parent = "resources"
  title = "Sun and Moon Almanac"

[[main]]
  name = "General Astronomy"
  url = "tags/astronomy"
  weight = 10
  parent = "resources"

[[main]]
  name = "Observer Resources"
  url = "tags/observer"
  weight = 20
  parent = "resources"

[[main]]
  name = "Outreach Resources"
  url = "tags/outreach"
  weight = 30
  parent = "resources"

[[main]]
identifier = "news"
name = "News"
weight = 80
title = "WASI News and Announcements"

[[main]]
  name = "All"
  url = "post"
  weight = 100
  parent = "news"

[[main]]
  name = "Star*Points"
  url = "tags/star-points"
  weight = 20
  parent = "news"

[[main]]
  name = "Announcements"
  url = "tags/announcements"
  weight = 30
  parent = "news"

[[main]]
  name = "Newsletter"
  url = "tags/newsletter"
  weight = 40
  parent = "news"


[[social]]
  name = "GitHub"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-github'><use href='images/feather/feather-sprite.svg#github'/></svg>"
  url = "https://github.com/Westminster-Astronomical-Society"
  weight = 10
  title = "Visit the GitHub project"

[[social]]
  name = "Bsky"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-bsky'><use href='images/feather/feather-sprite.svg#bsky'/></svg>"
  url = "https://bsky.app/profile/wasi-astro.bsky.social"
  weight = 20
  title = "Contact us on Bsky"

[[social]]
  name = "Xitter"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-xitter'><use href='images/feather/feather-sprite.svg#xitter'/></svg>"
  url = "https://twitter.com/WASI_Astro/"
  weight = 20
  title = "Contact us on Xitter"

[[social]]
  name = "Youtube"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-youtube'><use href='images/feather/feather-sprite.svg#youtube'/></svg>"
  url = "https://www.youtube.com/@westminsterastronomicalsoc1858"
  weight = 30
  title = "Visit our YouTube channel"

  [[social]]
  name = "Facebook"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-facebook'><use href='images/feather/feather-sprite.svg#facebook'/></svg>"
  url = "https://www.facebook.com/groups/wasi.contact/"
  weight = 40
  title = "Visit our Facebook page"